mixed-port: 8888
redir-port: 8890
allow-lan: true
mode: rule
ipv6: true
log-level: info
external-controller: 0.0.0.0:8080
secret: ""
hosts: ~
dns:
  enable: true
  listen: 127.0.0.1:1053
  ipv6: true
  default-nameserver:
    - 223.5.5.5
    - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - msftconnecttest.com
    - "*.msftconnecttest.com"
    - msftncsi.com
    - "*.msftncsi.com"
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - lens.l.google.com
    - stun.l.google.com
    - "*.n.n.srv.nintendo.net"
    - .apple.*
    - +.foo.com
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - https://doh.rixcloud.dev/dns-query
    - https://dns.alidns.com/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://doh.opendns.com/dns-query
    - https://dns.twnic.tw/dns-query
  fallback:
    - https://dns.twnic.tw/dns-query
    - https://dns.quad9.net/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://doh.qis.io/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.powerdns.org
  fallback-filter:
    geoip: true
    ipcidr:
      - 0.0.0.0/32
      - 127.0.0.1/32
      - 240.0.0.0/4

proxies:

# 服务器节点订阅
proxy-providers:
  # name: # Provider 名称
  #   type: http # http 或 file
  #   path: # 文件路径
  #   url: # 只有当类型为 HTTP 时才可用，您不需要在本地空间中创建新文件。
  #   interval: # 自动更新间隔，仅在类型为 HTTP 时可用
  #   health-check: # 健康检查选项从此处开始
  #     enable:
  #     url: 
  #     interval: 

  #
  # 「url」参数填写订阅链接
  #
  # 订阅链接可以使用 API 进行转换，如：https://sub.dler.io/
  #
  # 1.模式选择「进阶模式」 2.填写订阅链接 3.勾选「输出为 Node List」 4.「生成订阅链接」
  #

  ByWave: # 冲鸭机场订阅链接
    type: http
    url: "https://suo.yt/"
    interval: 3600
    path: ./Proxy/ByWave.yaml # 不同机场不同命名
    health-check:
      enable: true
      interval: 600
      url: https://cp.cloudflare.com/generate_204

  ByWave-hk: # 冲鸭机场订阅链接
    type: http
    url: "https://suo.yt/"
    interval: 3600
    path: ./Proxy/ByWavehk.yaml # 不同机场不同命名
    health-check:
      enable: true
      interval: 600
      url: https://cp.cloudflare.com/generate_204

  ByWave-us: # 冲鸭机场订阅链接
    type: http
    url: "https://suo.yt/"
    interval: 3600
    path: ./Proxy/ByWaveus.yaml # 不同机场不同命名
    health-check:
      enable: true
      interval: 600
      url: https://cp.cloudflare.com/generate_204

  ByWave-tw: # 冲鸭机场订阅链接
    type: http
    url: "https://suo.yt/"
    interval: 3600
    path: ./Proxy/ByWavetw.yaml # 不同机场不同命名
    health-check:
      enable: true
      interval: 600
      url: https://cp.cloudflare.com/generate_204

  ByWave-jp: # 冲鸭机场订阅链接
    type: http
    url: "https://suo.yt/"
    interval: 3600
    path: ./Proxy/ByWavejp.yaml # 不同机场不同命名
    health-check:
      enable: true
      interval: 600
      url: https://cp.cloudflare.com/generate_204

  ByWave-sg: # 冲鸭机场订阅链接
    type: http
    url: "https://suo.yt/"
    interval: 3600
    path: ./Proxy/ByWavesg.yaml # 不同机场不同命名
    health-check:
      enable: true
      interval: 600
      url: https://cp.cloudflare.com/generate_204

proxy-groups:
# 策略组示例请查阅 Clash 项目 README 以使用最新格式：https://github.com/Dreamacro/clash/blob/master/README.md

#
# 策略组说明
#
# 「MATCH」类似 Surge 的「Final」，此处用于选择白名单模式(PROXY 策略)和黑名单模式(DIRECT 策略)
#
# 「Streaming」和「StreamingSE」比较好理解，有专用于流媒体的节点就设置到其中，如果没有「StreamingSE」的需求可以连带 Rule 部分一起删掉，「Streaming」需至少保留 Rule，用「PROXY」即可。
#
# 「PROXY」是代理规则策略，它可以指定为某个节点或嵌套一个其他策略组，如：「自动测试」、「Fallback」或「负载均衡」的策略组，关于这 3 个策略组的具体示例可以看官方示例：https://github.com/Dreamacro/clash
#
  # 代理节点选择
  - name: "PORNGUARD"
    type: select
    proxies:
      - REJECT

  - name: "GFWLIST"
    type: select
    proxies:
      - PROXY
      - DIRECT

  # 白名单模式 PROXY, 黑名单模式 DIRECT, 不知道别动
  - name: "MATCH"
    type: select
    proxies:
      - PROXY
      - DIRECT

  # 代理节点选择
  - name: "PROXY"
    type: select
    proxies:
      - Fallback
      - DIRECT

  # 国际流媒体服务
  - name: "Microsoft"
    type: select
    proxies:
      - PROXY
      - HK

  # 国际流媒体服务
  - name: "Spotify"
    type: select
    proxies:
      - PROXY
      - HK

  # 国际流媒体服务
  - name: "Netflix"
    type: select
    proxies:
      - PROXY
      - HK
      - TW
      - SG
      - JP
      - US

  # 国际流媒体服务
  - name: "Google"
    type: select
    proxies:
      - PROXY
      - US

  # 国际流媒体服务
  - name: "YouTube"
    type: select
    proxies:
      - PROXY
      - US

  # 国际流媒体服务
  - name: "GoogleFCM"
    type: select
    proxies:
      - PROXY
      - US

  # 中国流媒体服务（面向海外版本）
  - name: "BilibiliHMT"
    type: select
    proxies:
      - PROXY
      - HK
      - TW
      - DIRECT

  # 中国流媒体服务（面向海外版本）
  - name: "DisneyPlus"
    type: select
    proxies:
      - PROXY
      - US

  # 手动选择节点订阅
  - name: "Fallback"
    type: fallback # 亦可使用 fallback 或 load-balance
    use:
      - ByWave

  # 手动选择节点订阅
  - name: "ByWave"
    type: select # 亦可使用 fallback 或 load-balance
    use:
      - ByWave

  # 手动选择节点订阅
  - name: "HK"
    type: select # 亦可使用 fallback 或 load-balance
    use:
      - ByWave-hk

  # 手动选择节点订阅
  - name: "TW"
    type: select # 亦可使用 fallback 或 load-balance
    use:
      - ByWave-tw


  # 手动选择节点订阅
  - name: "JP"
    type: select # 亦可使用 fallback 或 load-balance
    use:
      - ByWave-jp


  # 手动选择节点订阅
  - name: "US"
    type: select # 亦可使用 fallback 或 load-balance
    use:
      - ByWave-us


  # 手动选择节点订阅
  - name: "SG"
    type: select # 亦可使用 fallback 或 load-balance
    use:
      - ByWave-sg

# 关于 Rule Provider 请查阅：https://lancellc.gitbook.io/clash/clash-config-file/rule-provider

rule-providers:
# name: # Provider 名称
#   type: http # http 或 file
#   behavior: classical # 或 ipcidr、domain
#   path: # 文件路径
#   url: # 只有当类型为 HTTP 时才可用，您不需要在本地空间中创建新文件。
#   interval: # 自动更新间隔，仅在类型为 HTTP 时可用

  PORNGUARD:
    type: http
    behavior: classical
    path: ./RuleSet/Porn.yaml
    url: https://raw.githubusercontent.com/FaNGbABa/Clash/master/Config/Porn.yaml
    interval: 86400

  Microsoft:
    type: http
    behavior: classical
    path: ./RuleSet/Microsoft.yaml
    url: https://raw.githubusercontent.com/FaNGbABa/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Microsoft.yaml
    interval: 86400

  YouTube:
    type: http
    behavior: classical
    path: ./RuleSet/YouTube.yaml
    url: https://raw.githubusercontent.com/FaNGbABa/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/YouTube.yaml
    interval: 86400

  Google:
    type: http
    behavior: classical
    path: ./RuleSet/Google.yaml
    url: https://raw.githubusercontent.com/FaNGbABa/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Google.yaml
    interval: 86400

  GoogleFCM:
    type: http
    behavior: classical
    path: ./RuleSet/GoogleFCM.yaml
    url: https://raw.githubusercontent.com/FaNGbABa/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleFCM.yaml
    interval: 86400

  BilibiliHMT:
    type: http
    behavior: classical
    path: ./RuleSet/BilibiliHMT.yaml
    url: https://raw.githubusercontent.com/FaNGbABa/Clash/master/Config/BilibiliHMT.yaml
    interval: 86400

  DisneyPlus:
    type: http
    behavior: classical
    path: ./RuleSet/DisneyPlus.yaml
    url: https://raw.githubusercontent.com/FaNGbABa/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/DisneyPlus.yaml
    interval: 86400

  Spotify:
    type: http
    behavior: classical
    path: ./RuleSet/Spotify.yaml
    url: https://raw.githubusercontent.com/FaNGbABa/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Spotify.yaml
    interval: 86400

  Netflix:
    type: http
    behavior: classical
    path: ./RuleSet/Netflix.yaml
    url: https://raw.githubusercontent.com/FaNGbABa/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Netflix.yaml
    interval: 86400

  ProxyGFWlist:
    type: http
    behavior: classical
    path: ./RuleSet/ProxyGFWlist.yaml
    url: https://raw.githubusercontent.com/FaNGbABa/ACL4SSR/ACL4SSR/master/Clash/Providers/ProxyGFWlist.yaml
    interval: 86400

  China:
    type: http
    behavior: classical
    path: ./RuleSet/China.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml
    interval: 86400

  ChinaIP:
    type: http
    behavior: ipcidr
    path: ./Clash/Providers/ChinaIP.yaml
    url: https://raw.githubusercontent.com/FaNGbABa/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaIp.yaml
    interval: 86400

# 规则
rules:
  # Unbreak
  - RULE-SET,PORNGUARD,PORNGUARD

  - RULE-SET,Microsoft,Microsoft

  # (Streaming Media)
  - RULE-SET,YouTube,YouTube

  # (Streaming Media)
  - RULE-SET,Google,Google

  # (Streaming Media)
  - RULE-SET,GoogleFCM,GoogleFCM

  # (Streaming Media)
  - RULE-SET,BilibiliHMT,BilibiliHMT

  # (Streaming Media)
  - RULE-SET,DisneyPlus,DisneyPlus

  # (StreamingSE)
  - RULE-SET,Spotify,Spotify

  # (StreamingSE)
  - RULE-SET,Netflix,Netflix

  # (DNS Cache Pollution) / (IP Blackhole) / (Region-Restricted Access Denied) / (Network Jitter)
  - RULE-SET,ProxyGFWlist,PROXY

  # China Area Network
  - RULE-SET,China,DIRECT

  # Local Area Network
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT

  # （可选）使用来自 ipipdotnet 的 ChinaIP 以解决数据不准确的问题，使用 ChinaIP.yaml 时可禁用下列直至（包括）「GEOIP,CN」规则
  # - RULE-SET,ChinaIP,DIRECT
  # Tencent
  - IP-CIDR,119.28.28.28/32,DIRECT
  - IP-CIDR,182.254.116.0/24,DIRECT
  # GeoIP China
  - GEOIP,CN,DIRECT

  - MATCH,MATCH
