port: 8888
socks-port: 8890
allow-lan: false
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
experimental:
    ignore-resolve-fail: true
dns:
    enable: true
    listen: 127.0.0.1:1053
    default-nameserver:
      - 223.5.5.5
      - 114.114.114.114
      - 1.2.4.8
      - 123.206.21.48
      - 202.102.128.68
    ipv6: false
    enhanced-mode: fake-ip
    fake-ip-range: 198.10.0.1/16
    fake-ip-filter:
      - '*.lan'
      - 'stun.*.*.*'
      - 'stun.*.*'
      - 'time.windows.com'
      - 'time.nist.gov'
      - '*.ntp.org.cn'
      - '*.openwrt.pool.ntp.org'
      - 'time1.cloud.tencent.com'
      - 'time.ustc.edu.cn'
      - 'pool.ntp.org'
      - 'ntp.ubuntu.com'
      - '*.aliyun.com'
      - '*.time.edu.cn'
      - '.apple.*'
      - 'lens.l.google.com'
      - 'stun.l.google.com'
      - '*.music.163.com'
      - '*.126.net'
      - '*.kuwo.cn'
      - '*.y.qq.com'
      - '*.xiami.com'
      - '*.music.migu.cn'
      - '*.msftconnecttest.com'
      - '*.msftncsi.com'
      - 'localhost.ptlogin2.qq.com'
      - '*.*.*.srv.nintendo.net'
      - '*.*.stun.playstation.net'
      - 'xbox.*.*.microsoft.com'
      - '*.*.xboxlive.com'
    nameserver:
      - 119.29.29.29
      - 223.5.5.5
      - 'https://dns.alidns.com/dns-query'
    fallback:
      - 'https://dns.google/dns-query'
      - 'https://dns.sb/dns-query'
      - 'tls://dns.google:853'
      - 'tls://dns.sb:853'
    fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
      - 127.0.0.1/32
proxy-providers:
  Bywave:
    type: http 
    path: ./providers/Bywave.yaml
    url: ""
    interval: 10800
    health-check:
      enable: true
      url: "http://www.gstatic.com/generate_204"
      interval: 300
  Miaona!:
    type: http
    path: ./providers/Miaona.yaml
    url: ""
    interval: 10800
    health-check:
      enable: true
      url: "http://www.gstatic.com/generate_204"
      interval: 300
  Cloud-Wing:
    type: http
    path: ./providers/Cloud-Wing.yaml
    url: ""
    interval: 10800
    health-check:
      enable: true
      url: "http://www.gstatic.com/generate_204"
      interval: 300
proxy-groups:
  - name: PROXY
    type: select
    use:
      - Bywave
      - Miaona!
      - Cloud-Wing
  - name: bilibili
    type: select
    use:
      - Bywave
      - Miaona!
      - Cloud-Wing
    proxies:
      - DIRECT
  - name: Google
    type: select
    use:
      - Bywave
      - Miaona!
      - Cloud-Wing
  - name: TELEGRAM
    type: select
    use:
      - Bywave
      - Miaona!
      - Cloud-Wing
  - name: HBO GO
    type: select
    use:
      - Bywave
      - Miaona!
      - Cloud-Wing
  - name: NETFLIX
    type: select
    use:
      - Bywave
      - Miaona!
      - Cloud-Wing
  - name: GlobalMedia
    type: select
    use:
      - Bywave
      - Miaona!
      - Cloud-Wing
rule-providers:
  Porn:
    type: http
    behavior: classical
    path: ./Clash/master/RuleSet/Porn.yaml
    url: "https://cdn.jsdelivr.net/gh/FaNGbABa/Clash@master/Surge/RuleSet/Porn.list"
    interval: 10800
  Microsoft:
    type: http
    behavior: classical
    path: ./Clash/master/RuleSet/Microsoft.yaml
    url: "https://cdn.jsdelivr.net/gh/FaNGbABa/Clash@master/Surge/RuleSet/Microsoft.list"
    interval: 10800
  GoogleFCM:
    type: http
    behavior: classical
    path: ./Clash/master/RuleSet/GoogleFCM.yaml
    url: "https://cdn.jsdelivr.net/gh/FaNGbABa/Clash@master/Surge/RuleSet/GoogleFCM.list"
    interval: 10800
  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: .Clash/master/RuleSet/google.yaml
    interval: 86400
  Google:
    type: http
    behavior: classical
    path: ./Clash/master/RuleSet/Google.yaml
    url: "https://cdn.jsdelivr.net/gh/FaNGbABa/Clash@master/Surge/RuleSet/Google.list"
    interval: 10800
  bilibili:
    type: http
    behavior: classical
    path: ./Clash/master/RuleSet/BiliBiliHMT.yaml
    url: "https://cdn.jsdelivr.net/gh/FaNGbABa/Clash@master/Surge/RuleSet/BiliBiliHMT.list"
    interval: 10800
  HBO GO:
    type: http
    behavior: classical
    path: ./Clash/master/RuleSet/HBO.yaml
    url: "https://cdn.jsdelivr.net/gh/FaNGbABa/Clash@master/Surge/RuleSet/HBO.list"
    interval: 10800
  NETFLIX:
    type: http
    behavior: classical
    path: ./Clash/master/RuleSet/Netflix.yaml
    url: "https://cdn.jsdelivr.net/gh/FaNGbABa/Clash@master/Surge/RuleSet/Netflix.list"
    interval: 10800
  AmazonIp:
    type: http
    behavior: domain
    path: ./Clash/master/RuleSet/AmazonIp.yaml
    url: "https://cdn.jsdelivr.net/gh/FaNGbABa/Clash@master/Surge/RuleSet/AmazonIp.list"
    interval: 10800
  cncidr:
    type: http
    behavior: domain
    path: ./Clash/master/RuleSet/CNcidr.yaml
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    interval: 10800
  cnip:
    type: http
    behavior: domain
    path: ./Clash/master/RuleSet/CNip.yaml
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    interval: 10800
  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: .Clash/master/RuleSet/icloud.yaml
    interval: 10800
  Apple:
    type: http
    behavior: classical
    path: ./Clash/master/RuleSet/Apple.yaml
    url: "https://cdn.jsdelivr.net/gh/FaNGbABa/Clash@master/Surge/RuleSet/Apple.list"
    interval: 10800
  GlobalMedia:
    type: http
    behavior: classical
    path: ./Clash/master/RuleSet/GlobalMedia.yaml
    url: "https://cdn.jsdelivr.net/gh/FaNGbABa/Clash@master/Surge/RuleSet/GlobalMedia.list"
    interval: 10800
  TELEGRAM:
    type: http
    behavior: classical
    path: ./Clash/master/RuleSet/TELEGRAM.yaml
    url: "https://cdn.jsdelivr.net/gh/FaNGbABa/Clash@master/Surge/RuleSet/Telegram.list"
    interval: 10800
  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: .Clash/master/ruleset/lancidr.yaml
    interval: 10800
  DOMESTIC:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/FaNGbABa/Clash@master/Surge/RuleSet/domestic.list"
    path: .Clash/master/RuleSet/domestic.yaml
    interval: 10800
rules:
  - RULE-SET,Porn,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,Apple,DIRECT
  - RULE-SET,Microsoft,DIRECT
  - RULE-SET,TELEGRAM,TELEGRAM
  - RULE-SET,GoogleFCM,DIRECT
  - RULE-SET,google,Google,force-remote-dns
  - RULE-SET,Google,Google,force-remote-dns
  - RULE-SET,bilibili,bilibili
  - RULE-SET,HBO GO,HBO GO
  - RULE-SET,NETFLIX,NETFLIX
  - RULE-SET,AmazonIp,NETFLIX
  - RULE-SET,GlobalMedia,GlobalMedia
  - RULE-SET,DOMESTIC,DIRECT,no-resolve
  - RULE-SET,lancidr,DIRECT,no-resolve
  - RULE-SET,cncidr,DIRECT,no-resolve
  - RULE-SET,cnip,DIRECT,no-resolve
  - GEOIP,CN,DIRECT,no-resolve
  - GEOIP,,DIRECT,no-resolve
  - MATCH,,PROXY,force-remote-dns # dns-failed
